In [9]:
import numpy as np

In [10]:
random_num_generator = np.random.default_rng(0)

# Codes for sampling a p-TPM from the set of all integerized p-TPMs uniformly at random.

For all positive integers $n, p \geq 2$, define $\Delta^{n}_{p} := \{ (k_{1}, k_{2}, \ldots, k_{n}) : k_{i} \in \mathbb{Z}_{\geq 0}, \sum^{n}_{i = 1} k_{i} = p \}$. The following function samples from $\Delta^{n}_{p}$ uniformly. The output of this function is a 1D numpy array.

In [11]:
def uniform_sample_from_Delta_np(n, p):
    endpoints = random_num_generator.choice(np.arange(1, p + n, dtype=int), size=n - 1, replace=False)
    endpoints = np.append(endpoints, [0, p + n])
    endpoints.sort()
    
    output_array = np.array([endpoints[k] - endpoints[k - 1] - 1 for k in range(1, n + 1)], dtype=int)
    
    return output_array

For all positive integers $m, p \geq 2$, define $\mathcal{T}(m, p)$ to be the set of all $m \times m$ integerized $p$-TPMs. The following function samples from $\mathcal{T}(m, p)$ uniformly.

In [12]:
def uniform_sample_integerized_pTPM(m, p):
    output_array = np.zeros((m, m), dtype=int)
    
    for k in range(m):
        output_array[:, k] = uniform_sample_from_Delta_np(m, p)
        
    return output_array

For $k = 4001, 4001, \ldots, 6000$, sample a matrix $P$ from $\mathcal{T}(32, k)$. Save $P$ into a folder.

In [13]:
for k in range(4001, 6001):
    P = uniform_sample_integerized_pTPM(32, k)
    file_path = './random_pTPMs/dim32_pTPM_' + str(k)
    np.save(file_path, P)

[[ 11 293 195 ...   2   0  30]
 [ 54 247   4 ...  77  20  66]
 [ 68 482 162 ... 116  91  87]
 ...
 [ 96  16  32 ... 321 386   9]
 [138 162 143 ... 125 198   5]
 [133 279  43 ...  20  62 148]]
[[153  97 163 ...  44 124 203]
 [142  68 199 ... 112 264  28]
 [ 43  31  77 ... 238 116 236]
 ...
 [218 206 286 ...  28   2  53]
 [ 92  14 302 ...  58 154   4]
 [286 124 240 ... 193 355  66]]
[[ 33   5  92 ...   2 228 377]
 [ 62 129 243 ... 553  33  78]
 [ 68  81  52 ... 280 351  16]
 ...
 [ 11  76  12 ... 175  86  94]
 [284  56 268 ...  32  27 137]
 [ 65  69  74 ...  78  86 430]]
[[356 231  99 ...  38 120 449]
 [ 45  23  83 ...  19  44  19]
 [151 159  33 ... 319  10  80]
 ...
 [ 42 309  71 ...  98  18 193]
 [ 89 133  61 ...  61  74 285]
 [ 41 164  77 ...  68 520   0]]
[[428 325  36 ... 222  81 287]
 [116 259 109 ...   2 320 309]
 [ 16  36 193 ... 199  79 280]
 ...
 [ 32  94  92 ...  39 117   1]
 [ 74  92  31 ...  24 131  68]
 [ 15 195  95 ... 142  36 238]]
[[ 57  79 144 ...  60  35  15]
 [  1 120

# Investigate the number of positive entries of the randomly generated $32 \times 32$ p-TPMs.

Let's use $P_{4001}, P_{4002}, \ldots, P_{6000}$ to represent the $32 \times 32$ random $p$-TPMs.

In [14]:
dim32_L0_norm_list = []

for k in range(4001, 6001):
    dim32_filepath = './random_pTPMs/dim32_pTPM_' + str(k) + '.npy'
    P = np.load(dim32_filepath)
    dim32_L0_norm_list.append(np.count_nonzero(P))

In [15]:
dim32_count_summary = dict()

for k in range(1025):
    k_count = dim32_L0_norm_list.count(k)
    if k_count > 0:
        dim32_count_summary[k] = k_count

In [16]:
dim32_count_summary

{1008: 3,
 1009: 2,
 1010: 5,
 1011: 14,
 1012: 31,
 1013: 74,
 1014: 106,
 1015: 154,
 1016: 227,
 1017: 261,
 1018: 332,
 1019: 298,
 1020: 233,
 1021: 167,
 1022: 70,
 1023: 21,
 1024: 2}