In [1]:
import numpy as np
import random
import copy
import json

This function requires two inputs:
1. mat is a non-negative $p \times q$ numpy array (type int).
2. target_sum is a positive integer.

In [2]:
def adjust_matrix_to_pTPM(mat, target_sum):
    output = copy.deepcopy(mat)
    p, q = np.shape(output)
    
    for j in range(q):
        if np.sum(output[:, j]) < target_sum:
            difference = target_sum - np.sum(output[:, j])
            feasible_positions = list(range(p))
            
            for k in range(difference):
                chosen_pos = random.choice(feasible_positions)
                output[chosen_pos, j] += 1
            
        elif np.sum(output[:, j]) > target_sum:
            difference = np.sum(output[:, j]) - target_sum
            
            for k in range(difference):
                feasible_positions = [i for i in range(p) if output[i, j] > 0]
                chosen_pos = random.choice(feasible_positions)
                output[chosen_pos, j] -= 1
    
    return output

In [3]:
def round_and_convert(arr):
    """
    Rounds each element in a floating-point array to the nearest integer
    and converts the array's data type to int.
    
    Parameters:
        arr (np.ndarray): The input floating-point array.
        
    Returns:
        np.ndarray: An array of type int with each element rounded.
    """
    # np.rint rounds each element to the nearest integer (but still as a float)
    # .astype(int) converts the resulting array to integer type.
    return np.rint(arr).astype(int)

# Create $8 \times 8$ truncated 5300-TPMs

In [35]:
p = 5300

for k in range(10):
    fTPM_filepath = './8-by-8/dim8_fTPM_' + str(k) + '.npy'
    fTPM = np.load(fTPM_filepath)
    
    mat_after_rounding = round_and_convert(p * fTPM)
    truncated_pTPM = adjust_matrix_to_pTPM(mat_after_rounding, p)
    print('iteration:', k)
    print(np.sum(truncated_pTPM, axis=0))
    print()
    
    tTPM_filepath = './8-by-8 (trunc)/dim8_tTPM_' + str(k)
    np.save(tTPM_filepath, truncated_pTPM)

iteration: 0
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 1
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 2
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 3
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 4
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 5
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 6
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 7
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 8
[5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 9
[5300 5300 5300 5300 5300 5300 5300 5300]



# Create $16 \times 16$ truncated 5300-TPMs

In [36]:
p = 5300

for k in range(10):
    fTPM_filepath = './16-by-16/dim16_fTPM_' + str(k) + '.npy'
    fTPM = np.load(fTPM_filepath)
    
    mat_after_rounding = round_and_convert(p * fTPM)
    truncated_pTPM = adjust_matrix_to_pTPM(mat_after_rounding, p)
    print('iteration:', k)
    print(np.sum(truncated_pTPM, axis=0))
    print()
    
    tTPM_filepath = './16-by-16 (trunc)/dim16_tTPM_' + str(k)
    np.save(tTPM_filepath, truncated_pTPM)

iteration: 0
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 1
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 2
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 3
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 4
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 5
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 6
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 7
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 8
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]

iteration: 9
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300]



# Create $32 \times 32$ truncated 5300-TPMs

In [37]:
p = 5300

for k in range(10):
    fTPM_filepath = './32-by-32/dim32_fTPM_' + str(k) + '.npy'
    fTPM = np.load(fTPM_filepath)
    
    mat_after_rounding = round_and_convert(p * fTPM)
    truncated_pTPM = adjust_matrix_to_pTPM(mat_after_rounding, p)
    print('iteration:', k)
    print(np.sum(truncated_pTPM, axis=0))
    print()
    
    tTPM_filepath = './32-by-32 (trunc)/dim32_tTPM_' + str(k)
    np.save(tTPM_filepath, truncated_pTPM)

iteration: 0
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300]

iteration: 1
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300]

iteration: 2
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300]

iteration: 3
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300]

iteration: 4
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300]

iteration: 5
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 

# Create $64 \times 64$ truncated 5300-TPMs

In [38]:
p = 5300

for k in range(10):
    fTPM_filepath = './64-by-64/dim64_fTPM_' + str(k) + '.npy'
    fTPM = np.load(fTPM_filepath)
    
    mat_after_rounding = round_and_convert(p * fTPM)
    truncated_pTPM = adjust_matrix_to_pTPM(mat_after_rounding, p)
    print('iteration:', k)
    print(np.sum(truncated_pTPM, axis=0))
    print()
    
    tTPM_filepath = './64-by-64 (trunc)/dim64_tTPM_' + str(k)
    np.save(tTPM_filepath, truncated_pTPM)

iteration: 0
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 1
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300]

iteration: 2
[5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300 5300
 5300 5300 5300 5300 53